version: "3.9"
services:
  game:
    build:
      dockerfile: ./Dockerfile.game
      context: .
    image: dfs_game
    container_name: dfs_game_1
    ports:
      - "4002:80"
    volumes:
      - ./common:/common:ro
  murmur:
    build:
      context: ./mumble
    image: mumble_server
    container_name: mumble_server_1
    ports:
      - "3001:64738/tcp"
      - "3001:64738/udp"
      - "5001:50051"
