FROM node:lts-slim as builder
COPY ./common /common
COPY ./admin /admin
WORKDIR /admin
RUN npm install --silent
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /admin/build/ /usr/share/nginx/html
COPY ./admin/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
