version: "3.9"
services:
  admin:
    build:
      dockerfile: ./Dockerfile.admin
      context: .
    image: dfs_admin
    ports:
      - "8003:80"
  calibration_app:
    build:
      dockerfile: ./Dockerfile.calibration_app
      context: .
    image: dfs_calibration_app
    ports:
      - "4003:80"
  game:
    build:
      dockerfile: ./Dockerfile.game
      context: .
    image: dfs_game
    container_name: dfs_game_1
    ports:
      - "4002:80"
    volumes:
      - ./common:/common:ro
  murmur:
    build:
      context: ./mumble
    image: mumble_server
    container_name: mumble_server_1
    ports:
      - "3001:64738/tcp"
      - "3001:64738/udp"
      - "5001:50051"
