version: "3.9"
services:
  game:
    build:
      context: ./game
    image: dfs_game
    container_name: dfs_game_1
    ports:
      - "8001:80"
  murmur:
    build:
      context: ./mumble
    image: mumble_server
    container_name: mumble_server_1
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
      - "50051:50051"
    
